src/rofl/common/crofdpt.cc

During connection setup this patch will go into the state established
after config_reply is received. Hence the OF connections will be
established after exchanging features and config request/reply.

switch sooner into state established

---

src/rofl/common/crofbase.h

set new param raise=true to get a reference of an existing crofdpt
object. raise defaults to false to keep existing behavior.

crofbase: allow set_dpt without creation of a new instance

---

src/rofl/common/cthread.cpp

* changed lock to `AcquireReadWriteLock` because we do an `erase` within

changed lock to AcquireReadWriteLock

---

src/rofl/common/crofbase.h

set new param raise=true to get a reference of an existing crofctl
object. raise defaults to false to keep existing behavior.

crofbase: allow set_ctl without creation of a new instance

---

src/rofl/common/ctimespec.cpp
src/rofl/common/ctimespec.hpp

* fixed a crucial bug in operators `-` and `-=` in class ctimespec
* added new constructor for ctimespec to help with the fix
* performance improvement due to new constructor not calling system clock

fixes in ctimespec

---

src/rofl/common/ctimespec.cpp

in case timers are having the same timespec, the latter timer is
dropped in the set ordered_timers. This resolves the issue and checks
as well the timer_id.

timer: don't drop timers

---

src/rofl/common/ctimer.hpp
src/rofl/common/ctimespec.cpp
src/rofl/common/ctimespec.hpp

calls to rofl::ctimespec::now() can occur from differnt thread
contexts. This leads to an update of the timespec, that is returned as
reference.
Sanitizer log:
```
WARNING: ThreadSanitizer: data race (pid=3116)
Write of size 8 at 0x00000090c028 by thread T1 (mutexes: write M137):
#0 clock_gettime <null> (libtsan.so.0+0x0000000332eb)
#1 rofl::ctimespec::get_time(rofl::cclockid const&) /home/tobi/workspace/rofl-common/src/rofl/common/ctimespec.hpp:313 (crofsocktest+0x00000044b7cf)
#2 rofl::ctimespec::now(rofl::cclockid const&) /home/tobi/workspace/rofl-common/src/rofl/common/ctimespec.hpp:115 (crofsocktest+0x000000454ea1)
#3 rofl::cjrnentry::cjrnentry(unsigned int) /home/tobi/workspace/rofl-common/src/rofl/common/cjrnentry.hpp:53 (crofsocktest+0x000000454ea1)
#4 …
```

ctimespec: prevent data race

---

src/rofl/common/crofbase.cc
src/rofl/common/crofsock.cc

fcntl returns int and not long for F_GETFL. F_SETFL expects in as well
as a parameter.

fcntl return value an parameter fixup

---

src/rofl/common/crofsock.cc

* some OF agents don't like padding (i.e.: ofagent, ovs)
* tx debug log added

reset txbuffer before sending

---

examples/ethswctld/cfibentry.h
examples/ethswctld/cflowentry.h
src/rofl/common/cthread.cpp
src/rofl/common/cthread.hpp
test/rofl/common/crofchan/crofchantest.cpp

Removed thread environment locking, since env is thread local. Thread
environment is now a pure virtual interface. Thread running variable
was stored in global locked map, that is now replaced by a local atomic
running flag.

cthread: cleanup locking and api

---

src/rofl/common/crofsock.cc

bug report:
==================
WARNING: ThreadSanitizer: heap-use-after-free (pid=31910)
Read of size 8 at 0x7d780000f398 by thread T3 (mutexes: read M373):
#0 std::_Base_bitset<1ul>::_M_getword(unsigned long) const /usr/include/c++/5.3.1/bitset:411 (librofl_common.so.0+0x000001dd9ca2)
#1 std::bitset<32ul>::_Unchecked_test(unsigned long) const /usr/include/c++/5.3.1/bitset:1058 (librofl_common.so.0+0x000001dd9ca2)
#2 std::bitset<32ul>::test(unsigned long) const /usr/include/c++/5.3.1/bitset:1316 (librofl_common.so.0+0x000001dd9ca2)
#3 rofl::crofsock::flag_test(int) const ../../../../src/rofl/common/crofsock.h:785 (librofl_common.so.0+0x000001dd9ca2)
#4 rofl::crofsock::recv_message() ../../../../src/rofl/common/crofsock.cc:1838 (librofl_common.so.0+0x000001dc1386)
#5 …

crofsock: move call to backoff_reconnect

---

src/rofl/common/cthread.cpp

Despite the invalid return value check, pthread_timedjoin_np does not
join in time.

cthread: use pthread_join so finalize a thread

---

src/rofl/common/crofconn.cc

* reduced hello timeout values to close OF connection sufficiently early
* call handle_closed in case OF connection is expired due to missing hello messages

crofconn: hello values and expiration

---

src/rofl/common/crofbase.h

in case a class inherits from crofbase and the class is having its own
thread, the callbacks to crobase have to be callable.

crofbase: prevent shadowing of cthread callbacks

---

src/rofl/common/crofconn.cc

* break out of loop if 'rxqueues' does not contain any messages instead of looping until 'num < rxweights' is reached

loop optimization in handle_rx_messages

---

src/rofl/common/ctimespec.hpp

* `get_time()` has been removed because it will never be used because `get_time(const cclockid &clk_id =  clockid(CLOCK_MONOTONIC))` does have a default parameter set and basically does the same

remove_ambiguous_get_time

---

src/rofl/common/crofsock.cc

`OFPT_BARRIER_REPLY` are queued into `QUEUE_FLOW`, to be in line with `OFPT_BARRIER_REQUEST`

barrier_reply_into_queue_flow

---

src/rofl/common/crofsock.h

Using the appropriate enum enables to omit check of `__flag` parameter.

simplify_flag_set_flag_test

---

src/rofl/common/crofconn.h
src/rofl/common/ctimespec.cpp

* since `outqueue_type_t` has been made public it can be used as parameter

Use queue type enum

---

src/rofl/common/openflow/cofportstats.h

OFPP_ALL is not a valid port for this message type.

fix default port of cofport_stats_request

---

src/rofl/common/openflow/experimental/matches/Makefile.am
src/rofl/common/openflow/experimental/matches/ofdpa_matches.cc
src/rofl/common/openflow/experimental/matches/ofdpa_matches.h

this patch adds four OFDPA related experimental matches:
- coxmatch_ofb_vrf
- coxmatch_ofb_ovid
- coxmatch_ofb_allow_vlan_translation
- coxmatch_ofb_actset_output

OFDPA matches

---

src/rofl/common/crofsock.cc

as this suppresses reconnect attempts, check for DELETE_IN_PROGRESS is sufficient

 crofsock: do not check for STATE_IDLE in handle_timeout()

---

CHANGES
src/rofl/common/openflow/messages/cofmsg.cc

Padding fields should contain value 0. rofl-common did not ensure this behaviour as defined by openflow 1.3.5 properly. This patch fixes this bug.

ensure all padding fields are set to value 0

---

tools/rpmbuild/SPECS/rofl-common.spec.in

g++ was missing so far in the spec file. This is added now and will fix
builds on copr for F29+.

rpmbuild: add missing build requirement

---

src/rofl/common/cthread.cpp

Fix the following errors/warning when compiling against OpenSSL 3.0 or
newer:
```
| ../../../../git/src/rofl/common/cthread.cpp: In static member function 'static void rofl::cthread::openssl_initialize()':
| ../../../../git/src/rofl/common/cthread.cpp:37:23: warning: 'int ERR_load_ERR_strings()' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
|    37 |   ERR_load_ERR_strings();
|       |   ~~~~~~~~~~~~~~~~~~~~^~
| In file included from /tmp/kirkstone/work/cortexa9-vfp-poky-linux-gnueabi/rofl-common/0.13.4-r0/recipe-sysroot/usr/include/openssl/cryptoerr.h:17,
|                  from /tmp/kirkstone/work/cortexa9-vfp-poky-linux-gnueabi/rofl-common/0.13.4-r0/recipe-sysroot/usr/include/openssl/crypto.h:38,
|                  from …
```

cthread: fix compilation with OpenSSL 3.0+

---

examples/ethswctld/cdaemon.cc
test/rofl/common/crofchan/crofchantest.cpp
test/rofl/common/crofsock/crofsocktest.cpp

While trying to debug a race condition I stumbled upon the issue that rofl-common and its tests weren't compiling due to warnings (and warnings being treated as errors).
Fix this by fixing the warnings, i.e. add the missing include, and replace the deprecated calls of `pthread_yield()` with their replacement `sched_yield()` (which is called by pthread_yield() anyway).
Note that this does not allow all tests to succeed, the tests using SSL sockets will require additional changes on top.

fix build with newer libc versions

---

src/rofl/common/crofsock.cc

PR #128 noticed a deprecation for pthread_yield in crofsocktest and crofchantest, but did not address the same function call in crofsock. This PR complements that behavior.

crofsock: use sched_yield() instead of pthread_yield()
