- CHANGES
- src/rofl/common/openflow/cofgroupmod.cc
- src/rofl/common/openflow/cofgroupmod.h
- src/rofl/common/openflow/messages/cofmsg_group_mod.cc
- src/rofl/common/openflow/messages/cofmsg_group_mod.h
- test/rofl/common/openflow/Makefile.am
- test/rofl/common/openflow/cofgroupmod_test.cc
- test/rofl/common/openflow/cofgroupmod_test.h
- addresses issues #6 and #7
- ryu tests not done yet
> revision of classes cofmsg_group_mod and cofgroupmod

- src/rofl/common/openflow/messages/cofmsg_group_mod.cc
> fix groupmod message

- src/rofl/common/openflow/cofmatch.cc
- src/rofl/common/openflow/cofmatch.h
- src/rofl/common/openflow/coxmatch.cc
- src/rofl/common/openflow/coxmatch.h
- src/rofl/common/openflow/coxmatches.cc
- src/rofl/common/openflow/coxmatches.h
- src/rofl/common/openflow/experimental/matches/capwap_matches.h
- src/rofl/common/openflow/experimental/matches/gre_matches.h
- src/rofl/common/openflow/experimental/matches/gtp_matches.h
- src/rofl/common/openflow/experimental/matches/pppoe_matches.h
- src/rofl/common/openflow/experimental/matches/wlan_matches.h
- src/rofl/common/openflow/openflow_common.h
- test/rofl/common/openflow/cofflowstatsarray_test.cc
- test/rofl/common/openflow/coxmatch_test.cc
- test/rofl/common/openflow/coxmatch_test.h
- test/rofl/common/openflow/coxmatches_test.cc
* refactor coxmatch to gain more type safety
* spec compliant experimenter matches
> Coxmatch refactoring and experimenter oxm

- CHANGES
- src/rofl/common/crofsock.cc
- src/rofl/common/crofsock.h
fixed stalling situation in crofsock::handle_read() under higher load
> Akoepsel/devel 0.6/crofsock

- CHANGES
- src/rofl/common/logging.cc
- src/rofl/common/logging.h
making class indent thread aware, improved debug output
> making class indent thread aware, improved debug output

- CHANGES
- src/rofl/common/crofconn.cc
- src/rofl/common/crofconn.h
- src/rofl/common/crofqueue.h
- src/rofl/common/crofsock.cc
- src/rofl/common/crofsock.h
> added flow control mechanism for throttling socket in high load situations

- src/rofl/common/crofbase.cc
- src/rofl/common/crofbase.h
- src/rofl/common/crofchan.h
- src/rofl/common/crofconn.cc
- src/rofl/common/crofconn.h
- src/rofl/common/crofdpt.cc
- src/rofl/common/crofqueue.h
- src/rofl/common/crofsock.cc
- src/rofl/common/crofsock.h
- src/rofl/common/cthread.cpp
- test/rofl/common/crofbase/crofbasetest.cpp
- test/rofl/common/crofbase/crofbasetest.hpp
- test/rofl/common/crofchan/crofchantest.cpp
- test/rofl/common/crofchan/crofchantest.hpp
* revised reconnect strategy
* more valgrind tests
> reconnect strategy / valgrind tests

- src/rofl/common/crofconn.cc
- src/rofl/common/openflow/cofmeterconfig.cc
- src/rofl/common/openflow/cofmeterconfig.h
- src/rofl/common/openflow/cofmeterconfigarray.cc
- src/rofl/common/openflow/cofmeterconfigarray.h
- src/rofl/common/openflow/cofmeterstats.cc
- src/rofl/common/openflow/cofmeterstats.h
- src/rofl/common/openflow/cofmeterstatsarray.cc
- src/rofl/common/openflow/cofmeterstatsarray.h
- src/rofl/common/openflow/cofports.cc
- src/rofl/common/openflow/cofports.h
- src/rofl/common/openflow/cofportstatsarray.h
- src/rofl/common/openflow/cofqueuestats.cc
- src/rofl/common/openflow/cofqueuestats.h
- src/rofl/common/openflow/cofqueuestatsarray.cc
- src/rofl/common/openflow/cofqueuestatsarray.h
- test/rofl/common/openflow/messages/cofmsgfeatures/cofmsgfeaturestest.cpp
Revised code for segmentation and reassembly of openflow multipart messages
> Segmentation and reassembly

- .travis.yml
- CHANGES
- configure.ac
- src/rofl/common/cthread.cpp
- src/rofl/common/cthread.hpp
- src/rofl/common/exception.hpp
rofl::cthread:
* add asserts to thread handlers
* cthread: ignore signals in event loop
rofl::exception:
* improve exception handling
> minor improvements to rofl::cthread and rofl::exception

- tools/rpmbuild/SPECS/rofl_common.spec.in
* missing changelog for 0.10.2
* missing devel dependency
> updated spec file

- src/rofl/common/cmemory.cc
- src/rofl/common/cpacket.h
- src/rofl/common/crofdpt.h
* fixed some important issues found by sanitizer
> Sanitize (crucial)

- src/rofl/common/exception.hpp
As not all compilers are C11 yet, the use of "auto" fails for my gcc 5.4
(5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4))
> Exception fix gcc54

- src/rofl/common/crandom.cc
- src/rofl/common/openflow/cofgroupstats.cc
* crandom: invalid call to open fixed
* cofgroupstats: removed unnecessary operations
> cleanup and fixes found with scan-build

- src/rofl/common/crofchan.h
- src/rofl/common/crofconn.cc
- src/rofl/common/crofconn.h
- src/rofl/common/crofsock.h
- solves issues found by sanizier that may not be critical though
> Optional sanitize

- test/rofl/common/crofchan/crofchantest.cpp
- test/rofl/common/crofqueue/crofqueuetest.cpp
- test/rofl/common/crofsock/crofsocktest.hpp
- test/rofl/common/openflow/messages/cofmsgecho/cofmsgechotest.cpp
> tests: fix allocation errors

- examples/controller/controller.cpp
- examples/ethswctld/cetherswitch.cc
- examples/ethswctld/cetherswitch.h
- examples/ethswctld/cfibentry.cc
- examples/ethswctld/cfibentry.h
- examples/ethswctld/cfibtable.h
- examples/ethswctld/cflowtable.h
- examples/tcpserver/tcpserver.h
- src/rofl/common/cdpid.h
- src/rofl/common/cdptid.h
- src/rofl/common/cjrnentry.hpp
- src/rofl/common/crofbase.cc
- src/rofl/common/crofbase.h
- src/rofl/common/crofdpt.cc
- src/rofl/common/crofdpt.h
- src/rofl/common/openflow/messages/cofmsg_features.h
this moves cdpid and cdptid to typedefs
> Simplify IDs

- configure.ac
currently the tests exceed the 99 char limit of tar-v7, so swap to tar-pax
> include tests in dist release

- examples/ethswctld/cetherswitch.cc
- examples/ethswctld/cfibentry.cc
- examples/ethswctld/cflowentry.cc
- src/rofl/common/crofbase.cc
- src/rofl/common/crofchan.h
- src/rofl/common/crofconn.cc
- src/rofl/common/crofsock.cc
- src/rofl/common/cthread.cpp
- src/rofl/common/cthread.hpp
* fix heap-use-after-free in crofconn
* crofbase: return if accept fails with EAGAIN
* cthread: set name of thread
* crofbase: get_conn cannot be called
> several updates related to threading

- src/rofl/common/crofbase.cc
- src/rofl/common/crofconn.cc
- src/rofl/common/crofsock.cc
* output correct OF version number 
* formatting
> minor improvements

- src/rofl/common/openflow/coxmatch.cc
- src/rofl/common/openflow/coxmatch.h
- src/rofl/common/openflow/experimental/matches/pppoe_matches.h
print ppp(oe) related experimental OpenFlow extensible matches
> coxmatch: ppp outputter

- src/rofl/common/openflow/messages/cofmsg_features.h
* add parent class to copy assignment operator
> fix copy assignment operator

- examples/controller/controller.cpp
- examples/controller/controller.hpp
- examples/datapath/datapath.cpp
- examples/datapath/datapath.hpp
- examples/tcpclient/tcpclient.h
- src/rofl/common/crofbase.cc
- src/rofl/common/crofbase.h
* spelling correction of 'handle_conn_congestion_occurred'
> spelling correction - API change

- src/rofl/common/openflow/cofportstats.h
I would love to see port_stats as decimal numbers.
> port_stats_as_dec

- config/openssl.m4
- src/rofl/common/Makefile.am
- test/rofl/common/crofchan/crofchantest.hpp
this allows compilation using OpenSSL 1.1.
> update check for OpenSSL and ignore deprecation

- src/rofl/common/ctimespec.cpp
* fix operator in ctimespec... again...
> fix ctimespec operator

- .travis.yml
- src/rofl/common/crofsock.h
- src/rofl/common/cthread.cpp
- src/rofl/common/cthread.hpp
- src/rofl/common/openflow/cofhelloelemversionbitmap.h
- test/rofl/common/crofbase/Makefile.am
- test/rofl/common/crofbase/crofbasetest.cpp
- test/rofl/common/crofbase/crofbasetest.hpp
- test/rofl/common/crofbase/unittest.cpp
- test/rofl/common/crofchan/Makefile.am
- test/rofl/common/crofchan/crofchantest.cpp
- test/rofl/common/crofchan/unittest.cpp
- test/rofl/common/crofconn/crofconntest.cpp
- test/rofl/common/crofconn/crofconntest.hpp
- test/rofl/common/crofsock/Makefile.am
- test/rofl/common/crofsock/crofsocktest.cpp
- test/rofl/common/crofsock/crofsocktest.hpp
- test/rofl/common/crofsock/unittest.cpp
Several commits to stabilize and and cleanup rofl-common. Mostly found by using googles sanitizers as well as using llvm's static code analyzer. Details are found in the according commit messages.
> cleanup and stabilization

- CHANGES
- src/rofl/common/openflow/experimental/matches/capwap_matches.h
- src/rofl/common/openflow/experimental/matches/gre_matches.h
- src/rofl/common/openflow/experimental/matches/gtp_matches.h
- src/rofl/common/openflow/experimental/matches/ofdpa_matches.h
- src/rofl/common/openflow/experimental/matches/pppoe_matches.h
- src/rofl/common/openflow/experimental/matches/wlan_matches.h
- fixed bug in oxm_length for all experimental matches
- added OFDPA-2 related experimental matches
> experimental matches (OXM)

- CHANGES
- src/rofl/common/openflow/experimental/matches/capwap_matches.h
- src/rofl/common/openflow/experimental/matches/gre_matches.h
- src/rofl/common/openflow/experimental/matches/gtp_matches.h
- src/rofl/common/openflow/experimental/matches/ofdpa_matches.h
- src/rofl/common/openflow/experimental/matches/pppoe_matches.h
- src/rofl/common/openflow/experimental/matches/wlan_matches.h
- fixes bug in oxm_length for all experimental matches
- added OF-DPA related experimental matches (part 1)
> fixes bug in experimental matches and adds OF-DPA matches (part 1)

- src/rofl/common/openflow/cofdescstats.cc
- src/rofl/common/openflow/cofport.cc
- src/rofl/common/openflow/coftablefeatures.cc
* fix stringop-truncation
* pass correct len for strings in desc stats
> Strings (#111)

- src/rofl/common/openflow/cofaction.cc
- src/rofl/common/openflow/cofaction.h
- src/rofl/common/openflow/extensions/matches/ext244_matches.h
- test/rofl/common/openflow/cofaction/cofaction_test.cc
- test/rofl/common/openflow/cofaction/cofaction_test.h
-  cofaction.h => cofaction_set_field: add support for coxmatch_packet_register according to EXT-244 with zero oxm body
> devel ext244 for ofdpa
